/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bzxri2eernbslcegs4fa2ej2vu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s7hc52b6vvcdrkg5eelsmshmhu",
    "aws_cognito_identity_pool_id": "us-east-1:98ae454e-6dee-4704-b1cc-b5ad202cd246",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OTO56e63L",
    "aws_user_pools_web_client_id": "56635tc25cf5jjvl0t1s92f1n2",
    "oauth": {
        "domain": "apptravelers9f6fa8af-9f6fa8af-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.sostvl.com/alternative-login/,http://localhost:3000/alternative-login/",
        "redirectSignOut": "https://dev.sostvl.com/alternative-login/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
